library(ggplot2)
library(knitr)

source("R/helper_functions.R")

#' Creates a codebook
#' 
#' @param df Dataframe from which to construct the codebook
#' 
#' @param outname Base name to be used for output codebook files
#' 
#' @param overwrite if TRUE (default), overwrites existing files
#' 
#' @param reportTitle String to be passed to Codebook as title
#' 
#' @export
#' 

createCodebook <- function(df, outname = "test", savein = "~/dev", overwrite = T, reportTitle = "Data Dictionary", output = "html") {

  # construct names
  outRmd = paste0(outname, ".Rmd")
  outHtml = paste0(outname, ".html")
  
  filepathRmd <- file.path(savein, outRmd)
  filepathHtml <- file.path(savein, outHtml)
  
  # get database name
  dfname <- deparse(substitute(df))
  print(dfname)
  
  # delete existing files, if requested
  if (overwrite & file.exists(filepathRmd)) {
    file.remove(filepathRmd)
  }
  if (overwrite & file.exists(filepathHtml)) {
    file.remove(filepathHtml)
  }
  
  # open file connections
  fileConn <<- file(filepathRmd, "w") 

  ####################################### HEADER ################################
  
  ## write YAML preamble
  writer("---")
  writer(paste("title:", reportTitle))
  writer("subtitle: \"Autogenerated data dictionary\"")
  writer(paste("date:", Sys.time())) # OAK 20180720 change to prettier date/time
  if (output == "pdf") writer("output: pdf_document")
  if (output == "html") writer("output: html_document")
  if (output == "docx") writer("output: word_document")
  writer("---")
  
  ## include packages as a first chunk
  secretChunk.wrapper("library(ggplot2)\nlibrary(pander)")
  secretChunk.wrapper(paste0("dftest <- ", dfname))
  
  # write basic codebook information
  writer("## Overview")
  labels <- c("Number of observations", "Number of variables")
  values <- c(nrow(df), length(df))
  overview <- data.frame(Feature = labels, Value = values)
  writer(pander::pandoc.table.return(overview))
  writer("***")
  
  # write TOC
  writer("## Summary Table") # OAK 20180720 add hyperlinks to below sections for each variable
  
  tab <- calcSummaryTable(df)
  writer(pander::pandoc.table.return(tab, split.tables = Inf))
    # Variables <- names()
    # sumTab <- data.frame(labels = labs, Variable = vars, Class = classes, Unique = uniques, pMissing = missings")
  writer("***")
  
  ####################################### MAIN VARIABLE LOOP ################################
  
  # main variable loop: for each column, write out results
  writer("## Variables")
  varNames <- names(df)
  
  for (i in 1:length(df)) {
    
    # determine type
    var <- df[[i]]
    varName <- varNames[i]
    
    # write header
    # writer(paste0("### ", i, ") ", varName)) # OAK 20180720 remove numbering
    # writer(paste0("### ", varName))
    writer(paste0('### ', varName, ' <a id="', varName, '"></a>\n')) 
    # write label if one exists
    if (!is.null(attr(var, "label", exact = T))) {
      writer(paste ("####", attr(var, "label", exact = T))) # OAK 20180720 put label in codebookMetadataSummarize instead of as subheading
    }

    # get variable metadata and turn to rmarkdown table
    basicMeta <- codebookMetadataSummarize(var)
    basicMeta <- pander::pandoc.table.return(basicMeta)
    
    # get Variable data table
    datatable <- codebookDataTableSummarize(var)
    datatable <- pander::pandoc.table.return(datatable)
   
    # combine metadata table and data table into single string
    tab <- paste(basicMeta, "\n\n", datatable)

    # get Visualization for variable
    vis <- codebookVisualize(var,varName)
      # dt <- getDisplayType(var)
      # print(dt)
      # if (dt=="histogram"){
      #   kind<-"numeric"
      #   varPlot=factor(var)
      #   vis <- paste0("ggplot(data=dftest)+geom_histogram(aes(",varNames[i],"),color='black',bins=30)")
      # } else {
      #   kind<-"character"
      #   vis <- paste0("dftest[,'",paste0(varNames[i],"_new"),"']<-factor(dftest[,'",varNames[i],"'])\n
      #                 ggplot(data=dftest)+geom_bar(aes(",paste0(varNames[i],"_new"),"))")
      # }

    row.wrapper1(
      basicMeta,
      datatable,
      fig.wrapper(vis)
    )
    
    # added by OAK 20180720: print variable comments
    writer(paste0('\n**Comments:** ', attr(var, "comments")))
    
    # added by OAK 20180720: print variable derivation
    if (!is.null(attr(var, "derivation"))) {
      writer(paste0('\n**Derivation:** ', attr(var, "derivation")))
    }
    
    # added by OAK 20180720: go to top link
    writer('\n<a href="#top">Scroll to Top</a>\n')
    
    # write divider before moving to next variable
    writer("***")
    writer("\n")
  }

  ####################################### FOOTER ################################

  ## force flush and close connection
  
  flush(fileConn)
  close(fileConn)
  
  # knit document
  rmarkdown::render(filepathRmd, 'html_document', outHtml)
}



