---
title: "Plan"
author: "Omair A. Khan"
date: "7/20/2018"
output: html_document
---

# Development Plan

- code exception for character for Date type variables. print range of dates with timeline plot.
- make test case with neuropsych only
- remove "label" attribute from each variable
    + move attribute to "labels"
    + make sure class(var) shows proper class
- determine if variable exists in REDCap data and set is.derived = FALSE
- divide variables into distinct data frames by "project" (e.g. neuropsych, manual3T, etc.)
- add functionality for other attributes
    + units
    + table
    + is.derived
    + description/derivation text (put this on its own line)
    + comments (default: NONE; otherwise, include name of person, date of comment, and comment text; put this on its own line)
- add the following to the information printed for each variable
    + n
    + # missing
    + # distinct values
    + mean (if numeric)
    + min (if numeric)
    + various quartiles (if numeric)
    + max (if numeric)
    + values (if <=15 unique values) or levels (if categorical) with frequency & proportion
    + extremes (lowest and highest 5 values)
- create TOC page with all variables and their projects and create links to the page specific section for that variable

***

# Projects for Raw Data

## Static

- ABP Consent 
- APOE 
- Selected Eligibility 
- Cholesterol
- Atrial Fibrillation
- Antihypertensive
- Diabetes
- Antihypertensive - Beta Blockers
- Antihypertensive - Beta Blockers if not Drop
- Antihypertensive - ACE Inhibitors
- Antihypertensive - Angiotensin II Receptor Blockers
- Antihypertensive - Calcium Channel Blockers
- Antihypertensive - Potasium Sparing Diuretics
- Antihypertensive - Other
- Atrial Fibrillation Surgery

## Epoch 0

- MAP Eligibility
- MAP APOE

## Epoch 1
    
- MAP Enrollment
- MAP Cardiac MRI Analysis Epoch 1
- MAP Manual 3T Brain MRI Epoch 1
- MAP Manual 3T Brain MRI Breath Hold
- MAP Automated 3T Brain MRI Epoch 1
- MAP Automated 3T Brain MRI Breath Hold
- MAP Automated 3T Brain MRI Multiple Sessions
- MAP Clinical CSF Epoch 1
- MAP Biomarkers Epoch 1
- MAP SRT Error Analysis Epoch 1
- MAP Addendum Epoch 1

## Epoch 2

- MAP 18 Month
- MAP Cardiac MRI Analysis Epoch 2
- MAP Manual 3T Brain MRI Epoch 2
- MAP Automated 3T Brain MRI Epoch 2
- MAP Clinical CSF Epoch 2
- MAP Biomarkers Epoch 2

## Epoch 3

- MAP 36 Month 
- MAP Cardiac MRI Analysis Epoch 3
- MAP Manual 3T Brain MRI Epoch 3
- MAP Automated 3T Brain MRI Epoch 3
- MAP Clinical CSF Epoch 3
- MAP Biomarkers Epoch 3

## Epoch 4

- MAP 60 Month 
- MAP Manual 3T Brain MRI Epoch 4
- MAP Automated 3T Brain MRI Epoch 4
- MAP Clinical CSF Epoch 4

